const palavras = {
    Comidas: [
        "Açaí",
        "Arroz carreteiro",
        "Arroz doce",
        "Atum",
        "Azeite de oliva",
        "Baião de dois",
        "Banana à milanesa",
        "Banoffee",
        "Batata doce assada",
        "Batata frita",
        "Batata recheada",
        "Beijinho",
        "Bife a cavalo",
        "Bife à milanesa",
        "Bisnaguinha",
        "Bolacha",
        "Bolinho de arroz",
        "Bolinho de chuva",
        "Bolo de cenoura",
        "Bolo de chocolate",
        "Bolo de fubá",
        "Brigadeiro",
        "Brownie",
        "Burrito",
        "Cachorro-quente",
        "Caldo de cana",
        "Caldo verde",
        "Camarão",
        "Canjica",
        "Cappuccino",
        "Casquinha de sorvete",
        "Cenoura",
        "Cheesecake",
        "Churrasco",
        "Churros",
        "Cordeiro assado",
        "Coxinha",
        "Croissant",
        "Coca-Cola",
        "Cuca",
        "Cuscuz",
        "Donuts",
        "Eisbein",
        "Empada",
        "Empadão",
        "Enchilada",
        "Enroladinho de salsicha",
        "Esfiha",
        "Espaguete à bolonhesa",
        "Espetinho de carne",
        "Estrogonofe de carne",
        "Estrogonofe de frango",
        "Farofa",
        "Feijão tropeiro",
        "Feijoada",
        "Figo com presunto",
        "Filé mignon",
        "Fundue de Morango",
        "Frango a passarinho",
        "Frango assado",
        "Frango com quiabo",
        "Frango xadrez",
        "Frutos do mar",
        "Galinhada",
        "Guacamole",
        "Guioza",
        "Guaraná",
        "Hambúrguer",
        "Isca de peixe",
        "Iogurte natural",
        "Jacaré frito",
        "Joelho de porco",
        "Kibe assado",
        "Kibe frito",
        "Lamen",
        "Lasanha de carne",
        "Lasanha de berinjela",
        "Lombo assado",
        "Lula",
        "Linguiça",
        "Macarronada",
        "Macarons",
        "Mandioca frita",
        "Manjar de coco",
        "Maria-mole",
        "Moqueca capixaba",
        "Moqueca baiana",
        "Mousse de limão",
        "Mousse de maracujá",
        "Muffin",
        "Moqueca de peixe",
        "Nacci",
        "Nacho",
        "Niguiri",
        "Nhoque de batata doce",
        "Nuggets",
        "Omelete",
        "Ovo beneditino",
        "Ovo de Páscoa",
        "Paella",
        "Paçoca de pilão",
        "Pamonha",
        "Panetone",
        "Panqueca",
        "Pão de alho",
        "Pão de batata",
        "Pão de queijo",
        "Pão na chapa",
        "Pão sírio",
        "Pastel de carne",
        "Pastel de nata",
        "Pato no tucupi",
        "Pavê",
        "Pé de moleque",
        "Peixe frito",
        "Penne ao molho branco",
        "Petit gâteau",
        "Petit four",
        "Picanha na brasa",
        "Picolé",
        "Pimentão recheado",
        "Pipoca",
        "Pirão",
        "Pirogi",
        "Pizza de calabresa",
        "Pizza margherita",
        "Polenta frita",
        "Polpetone",
        "Porco agridoce",
        "Profiteroles",
        "Pudim de leite",
        "Quibebe",
        "Quiche de lorraine",
        "Quindim",
        "Quinoa com legumes",
        "Quiabo refogado",
        "Ratatouille",
        "Ravioli",
        "Risoto de camarão",
        "Risoto de cogumelos",
        "Roast beef",
        "Rocambole",
        "Rolo primavera",
        "Romeu e Julieta",
        "Rosti de batata",
        "Salada Caesar",
        "Salada de frutas",
        "Salada russa",
        "Salpicão",
        "Salsichão",
        "Sanduíche natural",
        "Sashimi",
        "Sertinejo",
        "Sopa de cebola",
        "Sopa de lentilha",
        "Sorvete",
        "Soufflé de queijo",
        "Spätzle",
        "Sushi",
        "Taco",
        "Tagliatelle",
        "Tapioca",
        "Tarê",
        "Tartare de salmão",
        "Tiramisu",
        "Tofu grelhado",
        "Tomate seco",
        "Torresmo",
        "Tortilla",
        "Torta de limão",
        "Torta de maçã",
        "Torta de morango",
        "Torta holandesa",
        "Tortei",
        "Truta grelhada",
        "Tucunaré assado",
        "Udon",
        "Vaca atolada",
        "Vatapá",
        "Vichyssoise",
        "Yakissoba",
    ],
};

export default palavras;
