const palavras = {
    Comidas: [
        "Açaí",
        "Arroz carreteiro",
        "Arroz doce",
        "Atum",
        "Azeite de oliva",
        "Alface",
        "Almôndega",
        "Alecrim",
        "Baião de dois",
        "Banana à milanesa",
        "Banoffee",
        "Batata doce assada",
        "Batata frita",
        "Batata recheada",
        "Beijinho",
        "Bife a cavalo",
        "Bife à milanesa",
        "Bisnaguinha",
        "Bolacha",
        "Bolinho de arroz",
        "Bolinho de chuva",
        "Bolo de cenoura",
        "Bolo de chocolate",
        "Bolo de fubá",
        "Brigadeiro",
        "Brownie",
        "Burrito",
        "Cachorro-quente",
        "Caldo de cana",
        "Caldo verde",
        "Camarão",
        "Canjica",
        "Cappuccino",
        "Casquinha de sorvete",
        "Cenoura",
        "Cheesecake",
        "Churrasco",
        "Churros",
        "Cordeiro assado",
        "Coxinha",
        "Croissant",
        "Coca-Cola",
        "Cuca",
        "Cuscuz",
        "Donuts",
        "Eisbein",
        "Empada",
        "Empadão",
        "Enchilada",
        "Enroladinho de salsicha",
        "Esfiha",
        "Espaguete à bolonhesa",
        "Espetinho de carne",
        "Estrogonofe de carne",
        "Estrogonofe de frango",
        "Farofa",
        "Feijão tropeiro",
        "Feijoada",
        "Figo com presunto",
        "Filé mignon",
        "Fundue de Morango",
        "Frango a passarinho",
        "Frango assado",
        "Frango com quiabo",
        "Frutos do mar",
        "Galinhada",
        "Guacamole",
        "Guaraná",
        "Goiabada",
        "Hambúrguer",
        "Isca de peixe",
        "Iogurte",
        "Jacaré frito",
        "Joelho de porco",
        "Kibe assado",
        "Kibe frito",
        "Lamen",
        "Lasanha de carne",
        "Lasanha de berinjela",
        "Lombo assado",
        "Lula",
        "Linguiça",
        "Macarronada",
        "Mandioca frita",
        "Maria-mole",
        "Moqueca",
        "Mousse de limão",
        "Mousse de maracujá",
        "Muffin",
        "Moqueca de peixe",
        "Nacho",
        "Nhoque de batata doce",
        "Nuggets",
        "Omelete",
        "Ovo de Páscoa",
        "Paçoca",
        "Pamonha",
        "Panetone",
        "Panqueca",
        "Pão de alho",
        "Pão de batata",
        "Pão de queijo",
        "Pão na chapa",
        "Pão Francês",
        "Pastel de carne",
        "Pavê",
        "Pé de moleque",
        "Peixe frito",
        "Petit gâteau",
        "Picanha",
        "Picolé",
        "Pimentão",
        "Pipoca",
        "Pirão",
        "Pizza de calabresa",
        "Pizza margherita",
        "Polenta frita",
        "Porco Assado",
        "Pudim",
        "Ravioli",
        "Risoto de camarão",
        "Risoto de cogumelos",
        "Rocambole",
        "Rolo primavera",
        "Romeu e Julieta",
        "Salada",
        "Salada de frutas",
        "Salpicão",
        "Salsichão",
        "Sanduíche natural",
        "Sashimi",
        "Sertinejo",
        "Sopa de cebola",
        "Sopa de lentilha",
        "Sorvete",
        "Sushi",
        "Taco",
        "Tapioca",
        "Tomate seco",
        "Torresmo",
        "Tortilha",
        "Torta de limão",
        "Torta de maçã",
        "Torta de morango",
        "Torta holandesa",
        "Uva",
        "Vaca atolada",
        "Yakissoba",
    ],
};

export default palavras;
