const perguntas = {
    Comidas: [
        "Você comeria essa comida com sorvete?",
        "Se essa comida lhe desse um poder, qual seria?",
        "Você prefere quente ou frio?",
        "Qual comida combina menos com isso?",
        "Você prefere comer com talheres ou com as mãos?",
        "Qual animal poderia fazer uma propaganda dessa comida na TV",
        "Essa comida poderia substituir qual parte de um esporte?",
        "Você comeria isso todos os dias ou só de vez em quando?",
        "Qual a parte favorita dessa sua comida?",
        "Demora mais de 30 minutos para preparar essa comida?",
        "Se essa comida representasse um estilo musical, qual seria?",
        "Essa comida sobreviveria a um apocalipse zumbi?",
        "Se fosse um vilão, qual seria o plano maligno dessa comida?",
        "Você esquentaria essa comida no micro-ondas",
        "Em que país essa comida é popular?",
        "Em uma briga contra um salame, quem ganharia?",
        "Se fosse personagem de desenho animado, qual personagem seria?",
        "Daria um bom sabor de chiclete?",
        "Você conseguiria morar numa casa feita disso?",
        "Você conseguiria guardar essa comida em um bolso sem amassar?",
        "Você comeu na ultima semana?",
        "Quando foi a ultima vez que você comeu?",
        "Essa comida está na sua lista de top 10 alimentos?",
        "Você comeria essa comida no café da manhã?",
        "Que tipo de evento essa comida não pode ser servido?",
        "Quem dos jogadores parece gostar mais dessa comida?",
        "Essa comida combina mais com festa ou com velório?",
        "Qual emoji representa melhor essa comida?",
        "Essa comida parece mais de rico ou de pobre?",
        "Se essa comida falasse, o que ela reclamaria?",
        "Essa comida é mais provável te salvar ou te matar?",
        "Se você derrubasse isso no chão, ainda comeria?",
        "Essa comida teria inveja de qual outra comida?",
        "Você comeria essa comida durante um primeiro encontro?",
        "Essa comida seria boa para arremessar em alguém?",
        "Se essa comida virasse um perfume, alguém compraria?",
        "Essa comida ficaria estranha se fosse azul?",
        "Qual bebida combina menos com essa comida?",
        "Você ficaria surpreso se encontrasse essa comida em um casamento?",
        "Você esconderia dinheiro dentro dessa comida?",
        "Se essa comida fosse um país, qual seria?",
        "Qual crime essa comida cometeria?",
        "Se essa comida tivesse um inimigo mortal, qual seria?",
        "Essa comida sobreviveria a uma queda de 10 andares?",
    ],
    Locais: [
        "Em troca de 20 mil reais, você moraria nesse lugar?",
        "Você levaria sua mãe para esse lugar?",
        "Você sobreviveria uma semana nesse lugar?",
        "Que tipo de pessoa frequenta esse lugar?",
        "Que filme deveria ser gravado nesse lugar?",
        "Poderia fazer um ótimo encontro nesse lugar?",
        "Você gostaria de trabalhar nesse lugar?",
        "Que tipo de crime poderia ser cometido nesse lugar?",
        "Qual personagem lembra desse lugar?",
        "Você pisaria nesse lugar descalço?",
        "Que emoji representa esse lugar?",
        "Você descobre que vai trabalhar nesse lugar pelo resto da sua vida, como você reagiria",
        "Você visitaria esse lugar sozinho à noite?",
        "Estando nesse lugar, o que faz se está apurado para fazer xixi?",
        "Você conseguiria dormir tranquilo nesse lugar?",
        "Esse lugar teria Wi-Fi?",
        "Você ficaria entediado nesse lugar?",
        "Você levaria seu cachorro para esse lugar?",
        "Esse lugar é mais quente ou frio?",
        "Você ficaria aí preso por 24 horas?",
        "Você passaria uma noite sozinho aí?",
        "Qual animal moraria nesse lugar?",
        "Você ficaria surpreso se alguém estivesse tomando sorvete nesse lugar?",
        "Você ficaria surpreso se alguém estivesse passeando com o cachorro nesse lugar?",
        "Você ficaria surpreso se alguém estivesse com uma arma nesse lugar?",
        "Você ficaria surpreso se alguém estivesse com um baralho de truco nesse lugar?",
        "Você já visitou esse lugar nos últimos 3 meses?",
        "Você gostaria de ir para esse lugar todos os dias ou de vez em quando?",
        "Nesse lugar, você vai por obrigação ou por que você gosta de ir?",
        "Qual seria a primeira coisa que você faria ao chegar nesse lugar?",
        "Você aceitaria passar um mês morando nesse lugar sem internet?",
        "Se esse lugar tivesse um cheiro, qual seria?",
        "Se você acordasse nesse lugar sem saber como chegou, entraria em pânico?",
        "Se você encontrasse um pinguim nesse lugar, ficaria surpreso?",
        "Qual seria a manchete de jornal mais provável envolvendo esse lugar?",
        "Se você perdesse seu celular nesse lugar, acreditaria que iria recuperá-lo?",
        "Você tiraria uma selfie nesse lugar?",
        "Você passaria 8 horas seguidas nesse lugar sem reclamar?",
        "Você se esconderia da polícia nesse lugar?",
        "Se esse lugar aparecesse em um filme, seria comédia ou terror?",
        "Se esse lugar fosse um aplicativo, para que serviria?",
        "Você faria uma festa de aniversário nesse lugar?",
        "Você deixaria seu carro estacionado nesse lugar por uma semana?",
        "Qual emoji NÃO combina com esse lugar?",
        "Você recomendaria esse lugar para um turista?"
    ],
    Jogadores: [
        "Qual profissão maluca combina com essa pessoa?",
        "Se ela fosse presa por um crime bobo, qual seria?",
        "Qual objeto representa essa pessoa?",
        "Você levaria essa pessoa para um encontro?",
        "Você conhece essa pessoa há mais de um ano?",
        "Você passaria 24 horas preso em um elevador com essa pessoa?",
        "Diga uma coisa que essa pessoa sabe fazer bem?",
        "Quem é mais provável de ser preso, você ou essa pessoa?",
        "Em qual filme essa pessoa iria se sair bem?",
        "Em uma luta contra o bob esponja, quem ganharia?",
        "Quem é mais provável se perder com o GPS, você ou essa pessoa?",
        "Você confiaria seu cartão de crédito para essa pessoa por uma semana?",
        "Essa pessoa seria eliminada cedo ou tarde em um reality show?",
        "Você ficaria surpreso se essa pessoa adotasse uma cobra?",
        "Você ficaria surpreso se essa pessoa virasse milionária?",
        "Você ficaria surpreso se essa pessoa aparecesse na TV?",
        "Qual superpoder combinaria com essa pessoa?",
        "Se essa pessoa fosse um aplicativo, qual seria?",
        "Qual animal combina mais com essa pessoa?",
        "Se essa pessoa fosse um vilão, qual seria seu plano maligno?",
        "Qual matéria escolar representa essa pessoa?",
        "Qual profissão essa pessoa jamais conseguiria exercer?",
        "Se essa pessoa abrisse uma empresa, o que ela venderia?",
        "Você viu essa pessoa ontem?",
        "Você se encontra com essa pessoa todos os dias, ou só de vez em quando?",
        "Você chamaria essa pessoa para o seu casamento como padrinho ou madrinha?"
    ],
};

export default perguntas;
